// One-off build helper: extracts the embedded level data (obj/map/mapw/targets)
// verbatim from the original PushBoxCanvas.java and emits web/js/levels.js.
// Run with: node web/tools/extract_levels.js
const fs = require("fs");
const path = require("path");

const javaPath = path.join(__dirname, "..", "..", "PushBoxCanvas.java");
const src = fs.readFileSync(javaPath, "utf8");

function extract(marker) {
  const i = src.indexOf(marker);
  if (i < 0) throw new Error("marker not found: " + marker);
  // find first '{' after the marker, then brace-match
  let j = src.indexOf("{", i + marker.length);
  let depth = 0, start = j;
  for (; j < src.length; j++) {
    if (src[j] === "{") depth++;
    else if (src[j] === "}") { depth--; if (depth === 0) { j++; break; } }
  }
  const literal = src.slice(start, j);
  // Java array initializer -> JS array literal (numbers + nested braces only)
  const jsLiteral = literal.replace(/\{/g, "[").replace(/\}/g, "]");
  // eslint-disable-next-line no-new-func
  return Function('"use strict"; return (' + jsLiteral + ");")();
}

const obj = extract("obj[][][] =");
const map = extract("map[][] =");
const mapw = extract("mapw[] =");
const targets = extract("targets[] =");

if (obj.length !== 33 || map.length !== 33 || mapw.length !== 33 || targets.length !== 33)
  throw new Error("unexpected level count: " + [obj.length, map.length, mapw.length, targets.length]);

// sanity: map size must be divisible by its width
map.forEach((m, i) => {
  if (m.length % mapw[i] !== 0)
    throw new Error("level " + i + " size " + m.length + " not divisible by width " + mapw[i]);
});

const out = `/*
  levels.js  --  level data extracted verbatim from the original
  PushBoxCanvas.java (the 'static final byte obj/map/mapw/targets' block).
  Generated by web/tools/extract_levels.js -- do not edit by hand.
*/
"use strict";
var LEVEL_DATA = {
  obj: ${JSON.stringify(obj)},
  map: ${JSON.stringify(map)},
  mapw: ${JSON.stringify(mapw)},
  targets: ${JSON.stringify(targets)}
};
`;

const outPath = path.join(__dirname, "..", "js", "levels.js");
fs.writeFileSync(outPath, out);
console.log("wrote", outPath);
console.log("levels:", obj.length, "map widths:", mapw.join(","));
